package com.example.data.model

/**
 * Morning Executive Summary domain models.
 * Powered by the Gemini API, synthesizing saved companies' latest news
 * with pending automation tasks and executive daily priorities.
 */

enum class ExecutiveMarketPosture(val label: String, val badgeColorHex: Long, val description: String) {
  AGGRESSIVE_EXECUTION(
    label = "AGGRESSIVE PIPELINE VELOCITY",
    badgeColorHex = 0xFF10B981,
    description = "High hiring velocity across target companies. Prioritize direct applications and recruiter outreach."
  ),
  TACTICAL_INTERVIEW_PREP(
    label = "TACTICAL INTERVIEW & INTEL",
    badgeColorHex = 0xFF00E5FF,
    description = "Active screening stages in progress. Focus on case-study frameworks and company earnings insights."
  ),
  HIGH_CONVICTION_OUTREACH(
    label = "STRATEGIC ALUMNI OUTREACH",
    badgeColorHex = 0xFFF59E0B,
    description = "Key leadership shifts reported. Warm introductions and referrals yield 4x interview conversion."
  ),
  PIPELINE_EXPANSION(
    label = "CORRIDOR EXPANSION",
    badgeColorHex = 0xFF8B5CF6,
    description = "Surging openings in Bengaluru tech hubs. Trigger automated job radar crawlers across tier-1 targets."
  )
}

/**
 * Breaking news and strategic interview angle for a saved/watched company.
 */
data class SavedCompanyNewsHighlight(
  val companyId: String,
  val companyName: String,
  val logoEmoji: String,
  val tier: String, // S+, S, A
  val headline: String,
  val newsSummary: String,
  val strategicImplication: String, // How the candidate leverages this news in interview or pitch
  val relevanceTag: String, // e.g. "Warehouse Robotics", "Quick Commerce Expansion", "Agentic AI"
  val sentimentLabel: String = "POSITIVE HIRING SIGNAL",
  val sentimentScore: Int = 92 // 0-100
)

/**
 * Individual pending automation task summarized for morning action.
 */
data class MorningAutomationTaskItem(
  val taskId: String,
  val title: String,
  val taskType: String, // JOB_RADAR, RESUME_REFRESH, RECRUITER_OUTREACH, INTERVIEW_PREP, MARKET_INTEL
  val priority: String, // CRITICAL, HIGH, MEDIUM, LOW
  val status: String, // IDLE, PENDING, RUNNING, COMPLETED
  val frequency: String,
  val recommendedTriggerReason: String,
  val targetEntities: String = "All Target Companies",
  val estimatedRuntimeSeconds: Int = 30
)

/**
 * Aggregated agenda of pending automation pipelines for the morning.
 */
data class MorningAutomationSummaryAgenda(
  val totalPendingTasksCount: Int,
  val highPriorityPendingCount: Int,
  val executionReadinessSummary: String,
  val pendingTasks: List<MorningAutomationTaskItem>
)

/**
 * High-leverage morning directive / priority item.
 */
data class ExecutiveActionDirective(
  val id: String,
  val priorityNumber: Int, // 1, 2, 3
  val title: String,
  val rationale: String,
  val targetEntityOrTask: String,
  val isCompleted: Boolean = false
)

/**
 * Complete Morning Executive Summary Report generated by Gemini API.
 */
data class MorningExecutiveSummaryReport(
  val summaryId: String = java.util.UUID.randomUUID().toString(),
  val dateFormatted: String, // e.g. "Monday, September 14, 2026"
  val timeFormatted: String, // e.g. "08:00 AM IST"
  val greeting: String, // e.g. "Good morning, Aditya."
  val macroExecutiveOverview: String,
  val marketPosture: ExecutiveMarketPosture,
  val companyNewsHighlights: List<SavedCompanyNewsHighlight>,
  val automationAgenda: MorningAutomationSummaryAgenda,
  val topExecutiveDirectives: List<ExecutiveActionDirective>,
  val tacticalClosingQuote: String,
  val audioBriefingScript: String,
  val isLiveGeminiGenerated: Boolean = true,
  val modelUsed: String = "gemini-3.5-flash",
  val latencyMs: Long = 0L,
  val generatedAtTimestamp: Long = System.currentTimeMillis()
)
