package com.example.data.model

/**
 * Pre-calibrated job requirement profile for target companies in the Bengaluru/Global tech ecosystem.
 */
data class TargetCompanyPresetJob(
  val id: String,
  val company: String,
  val role: String,
  val logoEmoji: String,
  val priorityTier: String,
  val requirementsText: String,
  val keyFocusAreas: List<String>
)

/**
 * Request payload for analyzing resume text against target company job requirements.
 */
data class ResumeJobComparisonRequest(
  val resumeText: String,
  val targetCompany: String,
  val targetRole: String,
  val jobRequirements: String
)

/**
 * Individual job requirement met by candidate's resume with concrete evidence.
 */
data class MatchedRequirementItem(
  val id: String,
  val requirementTitle: String,
  val resumeEvidence: String,
  val matchStrength: String = "STRONG", // STRONG, MODERATE, PARTIAL
  val importanceInRole: String = "CRITICAL" // CRITICAL, HIGH, MEDIUM
)

/**
 * Missing skill, metric, or experience gap identified by Gemini audit.
 */
data class RequirementGapItem(
  val id: String,
  val missingSkillOrCriteria: String,
  val severity: String = "CRITICAL_GAP", // CRITICAL_GAP, MODERATE_GAP, MINOR_GAP
  val whyCompanyDemandsThis: String,
  val actionableRemedy: String,
  val suggestedProjectOrProof: String
)

/**
 * Insider hiring criteria and culture bar-raiser insights for the target company.
 */
data class TargetCompanyCultureIntel(
  val companyName: String,
  val barRaiserFocus: String,
  val culturePillar: String,
  val commonInterviewTraps: List<String> = emptyList(),
  val recommendedAngle: String
)

/**
 * Actionable side-by-side bullet enhancement tailored directly to the target company's job requirements.
 */
data class ComparisonBulletEnhancement(
  val id: String,
  val originalBullet: String,
  val enhancedBullet: String,
  val targetedRequirement: String,
  val metricInfused: String,
  val keywordsAdded: List<String> = emptyList(),
  val rationale: String,
  val isApplied: Boolean = false
)

/**
 * Actionable checklist step for the candidate to execute before submitting their application.
 */
data class ComparisonActionStep(
  val priorityOrder: Int,
  val title: String,
  val details: String,
  val estimatedEffort: String = "1-2 hours",
  val category: String = "RESUME_EDIT" // RESUME_EDIT, PROOF_OF_WORK, INTERVIEW_PREP, NETWORKING
)

/**
 * Comprehensive feedback response generated by Gemini API comparing resume to job requirements.
 */
data class ResumeJobComparisonFeedback(
  val id: String = "comp_${System.currentTimeMillis()}",
  val targetCompany: String,
  val targetRole: String,
  val overallFitScore: Int, // 0-100
  val atsCompatibilityScore: Int, // 0-100
  val barRaiserFitScore: Int, // 0-100
  val readinessVerdict: String,
  val executiveSummary: String,
  val matchedRequirements: List<MatchedRequirementItem>,
  val requirementGaps: List<RequirementGapItem>,
  val companyCultureIntel: TargetCompanyCultureIntel,
  val bulletEnhancements: List<ComparisonBulletEnhancement>,
  val actionPlan: List<ComparisonActionStep>,
  val timestamp: String = "Just now",
  val isLiveGemini: Boolean = true,
  val modelUsed: String = "gemini-3.5-flash",
  val rawGeminiOutput: String = ""
)
