package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user's core competency tagged against target industries.
 */
@Entity(tableName = "core_competencies")
data class CoreCompetency(
  @PrimaryKey val id: String,
  val name: String,
  val category: String = "STRATEGY_OPERATIONS", // ANALYTICS_DATA, STRATEGY_OPERATIONS, AI_AUTOMATION, COMMERCIAL_FINANCE, PRODUCT_TECH
  val proficiency: String = "ADVANCED", // BEGINNER, INTERMEDIATE, ADVANCED, EXPERT
  val targetIndustries: List<String> = emptyList(), // e.g. ["Enterprise Cloud & SaaS", "FinTech & Payments"]
  val evidenceOrProofOfWork: String = "",
  val yearsOfExperience: Double = 1.0,
  val isVerified: Boolean = true,
  val lastAssessedTimestamp: Long = System.currentTimeMillis()
)

/**
 * Represents an industry-specific skill gap suggested by Gemini based on 2026 market trends.
 */
data class IndustrySkillGap(
  val id: String,
  val skillName: String,
  val targetIndustry: String,
  val gapSeverity: String = "HIGH_PRIORITY", // CRITICAL_GAP, HIGH_PRIORITY, EMERGING_ADVANTAGE
  val currentMarketTrend: String,
  val whyNeeded: String,
  val estimatedSalaryDelta: String = "+₹3L - ₹5L / yr",
  val recommendedAction: String,
  val suggestedRoles: List<String> = emptyList(),
  val isAddedToMyCompetencies: Boolean = false
)

/**
 * Comprehensive report generated by Gemini analyzing core competencies across target industries.
 */
data class SkillGapAnalysisReport(
  val targetIndustries: List<String>,
  val totalCompetenciesMapped: Int,
  val marketAlignmentScore: Int = 88, // 0 - 100
  val marketMacroSummary: String,
  val gaps: List<IndustrySkillGap>,
  val timestamp: Long = System.currentTimeMillis(),
  val modelUsed: String = "gemini-3.5-flash",
  val isLiveAiGenerated: Boolean = true
)

/**
 * Master catalog of target industries recognized in the career intelligence system.
 */
object TargetIndustryCatalog {
  val ALL_INDUSTRIES = listOf(
    "Enterprise Cloud & SaaS",
    "FinTech & Digital Payments",
    "Quick Commerce & Logistics",
    "Management Consulting & Strategy",
    "AI & Data Infrastructure",
    "E-Commerce & Retail Tech",
    "WealthTech & Capital Markets"
  )

  val INDUSTRY_COLORS = mapOf(
    "Enterprise Cloud & SaaS" to 0xFF00E5FF,
    "FinTech & Digital Payments" to 0xFF10B981,
    "Quick Commerce & Logistics" to 0xFFF59E0B,
    "Management Consulting & Strategy" to 0xFF818CF8,
    "AI & Data Infrastructure" to 0xFFA78BFA,
    "E-Commerce & Retail Tech" to 0xFFFB7185,
    "WealthTech & Capital Markets" to 0xFF34D399
  )
}
